### ISSUE TITLE
"Function require is undefined" when importing modules

### ISSUE THREAD

**Issue by fartinmartin** [motiondeveloper/adobe-script-starter#2]
I get a `Function require is undefined` when running a script that depends on a module. To recreate:

1. `git clone https://github.com/motiondeveloper/adobe-script-starter`
2. `npm i`
3. Edit `index.ts` line `18` from ~`alert("You selected: " + layer.name);`~ to `alert(aeq);`
4. `npm run dev`
5. Hit `F5`

I've also tested with a `test.ts` module exporting a simple string variable in the `src/` directory and received the same result. I believe this to be an issue with #1 as the [initial commit using Rollup](https://github.com/motiondeveloper/adobe-script-starter/tree/744d776aedc73873af49f536ffe65cbc660c992b) works for me! 

I tried editing the `.swcrc` file per [this issue](https://github.com/swc-project/swc/issues/198) on the swc repo, but didn't have any luck.

**Comment by timhaywood** [comment]
Hey, thanks for checking it out!

This is due to the fact swc doesn't do bundling by itself, which is why projects like Vite use a bundler like Rollup for the final production bundle.

SWCs has an experimental bundler I'm keen to give a go, just haven't gotten around to it yet. (https://swc.rs/docs/usage/bundling)

This repo is still experimental itself, so I'll add a note to the readme to make that clearer, and mention the lack of bundling.

Thanks! I'll post any relevant updates here too 👍

**Comment by timhaywood** [comment]
@fartinmartin if you're interested, I added bundling with SWCs spack. Feel free to try it out!

**Comment by fartinmartin** [comment]
Awesome! I'll be sure to check this out, thanks for the ping!
